name: Publish Packages

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100

    - name: Install dependencies
      run: dotnet restore ./src

    - name: Build
      run: dotnet build ./src --configuration Release --no-restore

    - name: Pack with dotnet
      run: dotnet pack ./src/ServiceLibrary.Model/ServiceLibrary.Model.csproj --output nuget-packages --configuration Release -p:PackageVersion=2.0.0

    - name: Push with dotnet
      run: dotnet nuget push nuget-packages/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
